# -*- coding: utf-8 -*-
"""Cópia de Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8XCoOnOeeEojuRJo8vfsRBlYRdks2OM
"""

print("hello world!")

print("Estou aprendendo Python")

"Estou aprendendo Python"

1+1

10-2

#multiplicação
2*2

#Divisão
10/2

a = 4
b = 6

a+b

#Criando uma váriavel do tipo string
frase = "Python para análise de dados"

frase[0]

frase[0:10]

frase[10:]

frase[:17]

frase.count('dados')

frase.lower()

frase.upper()

frase.replace('Python','Frases')

frase = frase.upper()

frase