# -*- coding: utf-8 -*-
"""Aula7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hl3kGa32_y-dtPC7jQ8K6kS8DzL8W6-U

**Analise Exploratoria**
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

df.shape

df.dtypes

df["Valor Venda"].sum()

df["custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head(1)

round(df["custo"].sum(), 2)

df["lucro"]  = df["Valor Venda"] - df["custo"]

df.head(1)

round(df["lucro"].sum(),2)

df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

df["Tempo_envio"].dtype

df.groupby("Marca")["Tempo_envio"].mean()

df.isnull().sum()

df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum()

pd.options.display.float_format = '{:20,.2f}'.format

lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum().reset_index()
lucro_ano

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["lucro"].sum()

df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.head()

df_2009.groupby(df_2009["Data Venda"].dt.month)["lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df_2009.groupby("Marca")["lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation='horizontal');

df_2009.groupby("Classe")["lucro"].sum().plot.bar(title="Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation='horizontal');

df["Tempo_envio"].describe()

plt.boxplot(df["Tempo_envio"]);

plt.hist(df["Tempo_envio"]);

df["Tempo_envio"].min()

df['Tempo_envio'].max()

df[df["Tempo_envio"] == 20]

df.to_csv("df_vendas_novo.csv", index=False)