# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHDzo0a1dIsYpswmB2P_Fe3RlpNnYvX-

**Estrutura de dados**

**Listas **
"""

animais=[1,2,3]

animais

animais = ["cachorro","gato", 12345,6.5]

animais

animais[0]

animais[3]

animais[0]="papagaio"

animais

animais.remove("gato")

animais

len(animais)

"gato" in animais

lista = [500,30,300,80,10]

max(lista)

min(lista)

animais.append("leão")

animais

animais.extend(["cobra",6])

animais

lista.sort()

lista

"""**Tuplas**"""

tp=("banana","maça",10,50)

tp[0]

tp.count("maça")

tp[0:2]

"""**Dicionário**"""

dc={"banana":10,"maça":20,"laranja":15,"uva":5}

dc["maça"]

dc["maça"]=25

dc

dc.keys()

dc.values()

dc.setdefault("limão",22)

dc